# Generated by Django 5.1 on 2024-08-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modified',
            new_name='modified_date',
        ),
    ]
